---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker-build
  pull: if-not-exists
  image: plugins/docker
  settings:
    dry_run: true
    repo: quay.io/ukhomeofficedigital/lev-web-ui
  when:
    event:
    - pull_request
