---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: cypress
  image: cypress/browsers:node16.14.0-chrome99-ff97
  commands:
  - npm ci
  - npm run test
  when:
    branch:
    - master
    event:
    - pull_request

- name: push_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/lev-web-ui
    tags:
      - "1.0.0-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:10}"
      - "1.0.0"
      - "1.0"
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME: ukhomeofficedigital+lev_web_ui
  when:
    branch:
      - master
    event:
      - push
