version: "3"
services:
  lev-web-ui:
    build: .
    ports:
    - "8001:8001"
    environment:
      API_HOST: mock-api
      API_PORT: 8080
      MOCK: "true"
      IAM_USER: minch.yoda@theforce.gov
      REDIS_CONNECTION_STRING: "redis://redis-service:6379"
#      REDIS_HOST: redis-service
#      REDIS_PORT: 6379
    depends_on:
    - redis-service
    - mock-api
  mock-api:
    image: 113355358853.dkr.ecr.eu-west-1.amazonaws.com/ho/hmpo/lev/api/lev-api:13f6c8908b156ab91537671146b3f179ff4a2b01
#    image: quay.io/ukhomeofficedigital/lev-api:0.18.1
    environment:
      MOCK: "true"
    ports:
    - "8080:8080"
  redis-service:
    image: redis
    ports:
    - "6379:6379"
