version: "3"
services:
  lev-web-ui:
    build: .
    ports:
      - "8001:8001"
    environment:
      NODE_ENV: local
      API_HOST: mock-api
      API_PORT: 8080
  mock-api:
    image: quay.io/ukhomeofficedigital/lev-api:0.18
    environment:
      MOCK: "true"
    ports:
      - "8080:8080"
  acceptance:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      - lev-web-ui
      - mock-api
    environment:
      - CYPRESS_baseUrl=http://lev-web-ui:8001
    command: npx cypress run
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json

