version: "3"
services:
  lev-web-ui:
    build: .
    ports:
    - "8001:8001"
    environment:
      NODE_ENV: local
      API_HOST: mock-api
      API_PORT: 8080
      REDIS_HOST: redis-service
      REDIS_PORT: 6379
    depends_on:
    - redis
    - mock-api
  mock-api:
    image: quay.io/ukhomeofficedigital/lev-api:0.18
    environment:
      MOCK: "true"
    ports:
    - "8080:8080"
  redis-service:
    image: redis
    ports:
    - "6379:6379"
