version: "3"
services:
  lev-web-ui:
    build:
      context: .
      args:
        HTTP_PROXY: ''
        HTTPS_PROXY: ''
    ports:
    - "8001:8001"
    environment:
      API_HOST: mock-api
      API_PORT: 8080
      MOCK: "true"
      REDIS_CONNECTION_STRING: "redis://redis-service:6379"
#      REDIS_HOST: redis-service
#      REDIS_PORT: 6379
    depends_on:
    - redis-service
    - mock-api
  mock-api:
    image: 113355358853.dkr.ecr.eu-west-1.amazonaws.com/ho/hmpo/lev/api/lev-api:13f6c8908b156ab91537671146b3f179ff4a2b01
    environment:
      MOCK: "true"
    ports:
    - "8080:8080"
  redis-service:
    image: redis
    ports:
    - "6379:6379"
  acceptance:
    build:
      context: .
      args:
        HTTP_PROXY: ''
        HTTPS_PROXY: ''
      dockerfile: Dockerfile-e2e
    depends_on:
      - lev-web-ui
      - mock-api
    environment:
      - CYPRESS_baseUrl=http://lev-web-ui:8001
    command: npm cypress run --headless --config-file ./cypress.config.js
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js

